<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header');
$user = Data::get('user');
$msg = Data::get('msg'); ?>


    <form class="form-signin" method="post" action="<?= Url::toRoute('user/edit') ?>">
        <h1 class="h3 mb-3 font-weight-normal">Editar</h1>
        <input type="text" value="<?=$user->fullname?>" name="fullname" class="form-control" placeholder="Nome Completo" required autofocus>
        <input type="email" value="<?=$user->email?>" name="email" class="form-control" placeholder="Email" required>
        <input type="password" value="<?=$user->pwd?>" name="pwd" class="form-control" placeholder="Palavra-Passe" required>
        <input type="date" name="birthday" class="form-control">
        <p><?=$msg?></p>
        <button class="btn btn-lg btn-dark btn-block" type="submit">Guardar</button>
    </form>

<?php Layout::includeLayout('footer') ?>