<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header');
$user = Data::get('user');
$scores = Data::get('scores'); ?>

    <div class="form-signin">
        <h1 class="h3 mb-3 font-weight-normal">Perfil: <?=$user->username?></h1>
        <input type="text" readonly value="<?=$user->fullname?>" name="fullname" class="form-control">
    </div>
    <div class="container">
        <table class="table table-sm table-striped">
            <thead>
            <th><h6>Id</h6></th>
            <th><h6>Data</h6></th>
            <th><h6>Jogador A</h6></th>
            <th><h6>Jogador B</h6></th>
            <th><h6>Resultado</h6></th>
            </thead>
            <tbody>
            <?php
            if (!is_null($scores)){
                foreach ($scores as $scorelist) {
                    ?>
                    <tr>
                        <td><?=$scorelist->id?></td>
                        <td><?=$scorelist->matchdate->format('Y-m-d') ?></td>
                        <td><?=$scorelist->playera?></td>
                        <td><?=$scorelist->playerb?></td>
                        <?php
                        if ($scorelist->playera < $scorelist->playerb){
                            echo "<td>Perdeu</td>";
                        }elseif ($scorelist->playera > $scorelist->playerb){
                            echo "<td>Ganhou</td>";
                        }else{
                            echo "<td>Empate</td>";
                        }
                        ?>
                    </tr>
                    <?php
                }
            }
            ?>
            </tbody>
        </table>
    </div>

<?php Layout::includeLayout('footer') ?>