<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header');

$msg = Data::get('mensagem');
$msg2 = Data::get('saldo');
$addBotao = Data::get('addBotao');
$removeBt = Data::get('removeBt');
?>
    <div class="container text-center">
        <br>
        <form class="form-signin" method="post" >
            <a class="btn btn-lg btn-danger"  data-toggle="modal" data-target="#exampleModal" <?= $msg ?>>Começar</a>

        </form>
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Atenção!!</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <?= $msg2 ?>
                    <?= $msg ?>

                </div>


                <form class="modal-footer" method="post" action="<?= Url::toRoute('game/game/discountBalance') ?>">
                    <button type="button" class="btn btn-danger" data-dismiss="modal" <?=$removeBt?>>Cancelar</button>
                    <button class="btn btn-success" type="submit" <?= $removeBt ?> >Ok</button>
                </form>



                <div class="container text-center" <?= $addBotao ?>>
                    <br>
                    <a href="<?= Url::toRoute('account/saldo')?>" class="btn btn-lg btn-danger">
                        Carregar Saldo
                    </a>
                    <br>
                </div>
                <br>
            </div>
        </div>
    </div>


<?php Layout::includeLayout('footer') ?>