<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header');
$msg = Data::get('mensagem');
?>
    <div class="container text-center">
        <br>
        <form class="form-signin" method="post" >
            <a class="btn btn-lg btn-danger"  data-toggle="modal" data-target="#exampleModal">Começar</a>
        </form>
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Atenção!!</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Ao premir o botão "Ok" serão-lhe retirados 0,05 euros.
                </div>
                <form class="modal-footer" method="post" action="<?= Url::toRoute('game/game') ?>">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Não</button>
                    <button class="btn btn-success" type="submit" >Ok</button>
                </form>
            </div>
        </div>
    </div>


<?php Layout::includeLayout('footer') ?>