<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $users = Data::get('users') ?>
<?php $user = Data::get('user') ?>

    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped">
                <thead>
                <th><h3>Id</h3></th>
                <th><h3>Nome</h3></th>
                <th><h3>Banido</h3></th>
                <th><h3>Admin</h3></th>
                </thead>
                <tbody>
                <?php foreach ($users as $userlist) {
                    if (strcmp($userlist->name, $user->name)){
                        ?>
                        <tr>
                            <td><?=$userlist->id?></td>
                            <td><?=$userlist->name?></td>
                            <td>
                                <?php
                                if ($userlist->banned==1){
                                    echo 'Sim';
                                }else{
                                    echo 'Não';
                                }
                                ?>
                            </td>
                            <td>
                                <?php
                                if ($userlist->admin==1){
                                    echo 'Sim';
                                }else{
                                    echo 'Não';
                                }
                                ?>
                            </td>
                            <td>
                                <a href="<?=Url::toRoute('backoffice/ban', $userlist->id)?>" class="btn btn-info" role="button">
                                    <?php
                                    if ($userlist->banned==1){
                                        echo 'Desbanir';
                                    }else{
                                        echo 'Banir';
                                    }
                                    ?>
                                </a>
                                <a href="<?=Url::toRoute('backoffice/admin', $userlist->id)?>" class="btn btn-info" role="button">
                                    <?php
                                    if ($userlist->admin==1){
                                        echo 'Tirar admin';
                                    }else{
                                        echo 'Tornar admin';
                                    }
                                    ?>
                                </a>
                                <a href="<?=Url::toRoute('backoffice/editar', $userlist->id)?>" class="btn btn-info" role="button">Editar</a>
                                <a href="<?=Url::toRoute('backoffice/destroy', $userlist->id)?>" class="btn btn-warning" role="button">Eliminar</a>
                            </td>
                        </tr>
                        <?php
                    }
                } ?>
                </tbody>
            </table>
        </div>
    </div>

<?php Layout::includeLayout('footer') ?>