    <!-- Footer -->
    <footer class="footer">
        <!-- Copyright -->
        <div class="container">© 2020 Copyright:
            <a href="#">Francisco Jacinto</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->

    <!-- JavaScript libs are placed at the end of the document so the pages load faster -->
    <?php
    use ArmoredCore\Facades\AssetBundler;
    use ArmoredCore\Facades\DebugRenderer;
    ?>
    <?=AssetBundler::js()?>
</body>
</html>