<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
?>

<div class="container">
    <div class="row text-center">
        <div class="col-md-4">
            <div class="row mt-3">
                <div class="col-md-12">
                    <button type="button" class="btn btn-lg btn-outline-danger">
                        1
                    </button>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <button type="button" class="btn btn-lg btn-outline-danger">
                        2
                    </button>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <button type="button" class="btn btn-lg btn-outline-danger">
                        3
                    </button>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <button type="button" class="btn btn-lg btn-outline-danger">
                        4
                    </button>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <button type="button" class="btn btn-lg btn-outline-danger">
                        5
                    </button>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <button type="button" class="btn btn-lg btn-outline-danger">
                        6
                    </button>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <button type="button" class="btn btn-lg btn-outline-danger">
                        7
                    </button>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <button type="button" class="btn btn-lg btn-outline-danger">
                        8
                    </button>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <button type="button" class="btn btn-lg btn-outline-danger">
                        9
                    </button>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="row mt-3">
                <div class="col-md-6">
                    <img class="rounded img-fluid" alt="Bootstrap Image Preview" src="<?=Asset::image('user.png')?>" />
                </div>
                <div class="col-md-6">
                    <img class="rounded img-fluid" alt="Bootstrap Image Preview" src="<?=Asset::image('pc.png')?>" />
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-6 border-dark">
                    <button type="button" class="btn btn-lg btn-outline-dark" disabled>
                        99
                    </button>
                </div>
                <div class="col-md-6 border-dark">
                    <button type="button" class="btn btn-lg btn-outline-dark" disabled>
                        99
                    </button>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <button type="button" class="btn btn-info">
                        Lançar os Dados
                    </button>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <img alt="Bootstrap Image Preview" src="<?=Asset::image('Dice/dieRed1.png')?>" />
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <img alt="Bootstrap Image Preview" src="<?=Asset::image('Dice/dieRed1.png')?>" />
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="row mt-3">
                <div class="col-md-12">
                    <button type="button" class="btn btn-lg btn-outline-info" disabled>
                        1
                    </button>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <button type="button" class="btn btn-lg btn-outline-info" disabled>
                        2
                    </button>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <button type="button" class="btn btn-lg btn-outline-info" disabled>
                        3
                    </button>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <button type="button" class="btn btn-lg btn-outline-info" disabled>
                        4
                    </button>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <button type="button" class="btn btn-lg btn-outline-info" disabled>
                        5
                    </button>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <button type="button" class="btn btn-lg btn-outline-info" disabled>
                        6
                    </button>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <button type="button" class="btn btn-lg btn-outline-info" disabled>
                        7
                    </button>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <button type="button" class="btn btn-lg btn-outline-info" disabled>
                        8
                    </button>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <button type="button" class="btn btn-lg btn-outline-info" disabled>
                        9
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>