<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data; ?>
<?php
$user = Data::get('userlayout');
$game = Data::get('game');
$acc = Data::get('account');
?>

<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="utf-8">
    <meta name="viewport"    content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author"      content="Francisco Jacinto & Gabriel Miranda">

    <title>Shut The Box</title>

    <?= AssetBundler::css()?>
</head>

<body>
    <!-- navbar -->
    <nav class="navbar navbar-expand-md bg-dark navbar-dark">
        <a class="navbar-brand" href="<?= Url::toRoute('home/menu')?>">Início</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <?php
            if (is_null($user)){
            ?>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="<?= Url::toRoute('user/login')?>">Entrar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= Url::toRoute('home/top')?>">Melhores Jogadores</a>
                </li>
            </ul>
            <?php
            }else{
            ?>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="<?= Url::toRoute('user/profile')?>"><?=$user->username?></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= Url::toRoute('game/menu')?>">Jogar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= Url::toRoute('home/top')?>">Melhores Jogadores</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= Url::toRoute('account/movimentos')?>">Movimentos da Conta</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= Url::toRoute('account/menu')?>"><?=$acc->valor?> €</a>
                </li>
                <?php
                if ($user->admin == 1){
                    ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= Url::toRoute('backoffice/show')?>">Backoffice</a>
                    </li>
                    <?php
                }
                ?>
                <li class="nav-item">
                    <a class="nav-link" href="<?= Url::toRoute('user/logout')?>">Sair</a>
                </li>
            </ul>
            <?php
            }
            ?>
        </div>
    </nav>
    <!-- /navbar -->