<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
?>
<?php $user = Data::get('user') ?>

<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="utf-8">
    <meta name="viewport"    content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author"      content="Francisco Jacinto & Gabriel Miranda">

    <title>Shut The Box</title>

    <?= AssetBundler::css()?>
</head>

<body>
    <!-- navbar -->
    <nav class="navbar navbar-expand-md bg-dark navbar-dark">
        <a class="navbar-brand" href="<?= Url::toRoute('home/inicio')?>">Início</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <?php
                if ($user != null){
                ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= Url::toRoute('home/perfil')?>"><?=$user->name?></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= Url::toRoute('game/menu')?>">Jogar</a>
                    </li>
                    <?php
                }else{
                    ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= Url::toRoute('home/login')?>">Entrar</a>
                    </li>
                    <?php
                }
                ?>
                <li class="nav-item">
                    <a class="nav-link" href="<?= Url::toRoute('home/top')?>">Melhores Jogadores</a>
                </li>
                <?php
                if ($user != null){
                    ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= Url::toRoute('home/logout')?>">Sair</a>
                    </li>
                    <?php
                }
                ?>
            </ul>
        </div>
    </nav>
    <!-- /navbar -->