<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
Layout::includeLayout('header');
$valor = Data::get('valor');
$montante = Data::get('soma');

?>


    <div class="container text-center">
        <br>
        <a href="<?= Url::toRoute('account/saldo')?>" class="btn btn-lg btn-danger">
            Carregar Saldo
        </a>
    </div>

<?php Layout::includeLayout('footer') ?>