<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header');
$account = Data::get('account');

?>


    <form class="form-signin" method="post" action="<?= Url::toRoute('account/saldo')?>">
        <input type="number" step='0.01' value='0.00' name="valor" class="form-control" id="#myAnchor" placeholder="Valor a carregar" required autofocus>
        <br>
        <input type="text" name="descricao" class="form-control" placeholder="Descricao" required autofocus>
        <br>
        <button class="btn btn-lg btn-dark btn-block" type="submit"  data-target="#exampleModal">Carregar</button>
        <!--data-toggle="modal"-->

    </form>

<?php Layout::includeLayout('footer') ?>