<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Data;

Layout::includeLayout('header') ?>
<?php $msg = Data::get('msg') ?>

    <form class="form-signin" method="post">
        <h1 class="h3 mb-3 font-weight-normal">Por favor inicie sessão</h1>
        <input type="text" name="name" class="form-control" placeholder="Nome" required autofocus>
        <input type="password" name="pwd" class="form-control" placeholder="Palavra-Passe" required>
        <p><?=$msg?></p>
        <button class="btn btn-lg btn-dark btn-block" name="btlogin" type="submit">Entrar</button>
        <button class="btn btn-lg btn-outline-dark btn-block" type="submit">Registar Novo</button>
    </form>

<?php Layout::includeLayout('footer') ?>