<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('header');
$user = Data::get('userlayout');
$top = Data::get('top');
$montante = Data::get('montante')?>

    <div class="form-signin">
        <h1 class="h3 mb-3 font-weight-normal">Top 10 Jogadores</h1>
    </div>
    <div class="container text-center">
        <table class="table table-bordered table-responsive-lg table-striped">
            <thead>
                <th><h6>Username</h6></th>
                <th><h6>Vitórias</h6></th>
                <th><h6>Derrotas</h6></th>
                <th><h6>Empates</h6></th>
            </thead>
            <tbody>
            <?php
            if (!is_null($top)){
                foreach ($top as $toplist) {
                ?>
                    <tr>
                        <td><?=$toplist->username?></td>
                        <td><?=$toplist->win?></td>
                        <td><?=$toplist->def?></td>
                        <td><?=$toplist->tie?></td>
                        <td>
                            <form method="post" action="<?= Url::toRoute('user/show') ?>">
                                <button type="submit" name="id" value="<?=$toplist->id?>" class="btn btn-lg text-info btn-block">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
                                        <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
                                    </svg>
                                </button>
                            </form>
                        </td>
                    </tr>
                <?php
                }
            }
            ?>
            </tbody>
        </table>
    </div>

<?php Layout::includeLayout('footer') ?>
